# Cloudflare Pages configuration for building the Next.js app in `web/`
# This file uses the Pages (beta) syntax expected by Wrangler on Cloudflare Pages.

# Required by Pages: the output directory relative to repo root
pages_build_output_dir = "web/.vercel/output/static"

# Build step executed by Pages
[build]
command = "cd web && npx @cloudflare/next-on-pages@1"


